import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: '#f1f5f9' },
  
  // Home Screen
  homeScroll: { flex: 1 },
  homeContent: { paddingHorizontal: 20, paddingTop: 20, paddingBottom: 40 },
  
  headerSection: { alignItems: 'center', marginBottom: 32 },
  logoBox: { 
    width: 80, 
    height: 80, 
    backgroundColor: '#4F46E5', 
    borderRadius: 24, 
    alignItems: 'center', 
    justifyContent: 'center',
    marginBottom: 16,
    shadowColor: '#4F46E5',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 8,
    elevation: 6,
  },
  mainTitle: { fontSize: 32, fontWeight: '800', color: '#0f172a', marginBottom: 8, letterSpacing: -0.5 },
  tagline: { fontSize: 14, color: '#64748b', textAlign: 'center' },

  // Input Wrapper
  inputWrapper: { 
    flexDirection: 'row', 
    alignItems: 'center', 
    backgroundColor: '#fff',
    borderRadius: 28,
    paddingHorizontal: 12,
    paddingVertical: 8,
    marginBottom: 20,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.08,
    shadowRadius: 8,
    elevation: 3,
    zIndex: 100,
  },
  plusMenuContainer: {
    position: 'relative',
    zIndex: 9999,
  },
  plusButton: { width: 40, height: 40, alignItems: 'center', justifyContent: 'center', borderRadius: 8 },
  plusButtonActive: { backgroundColor: '#f1f5f9' },
  plusMenu: {
    position: 'absolute',
    top: 48,
    left: 0,
    backgroundColor: '#fff',
    borderRadius: 12,
    padding: 8,
    minWidth: 140,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.15,
    shadowRadius: 12,
    elevation: 9999,
    zIndex: 9999,
  },
  menuItem: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 10,
    paddingHorizontal: 12,
    borderRadius: 8,
    gap: 10,
  },
  menuItemText: {
    fontSize: 14,
    color: '#0f172a',
    fontWeight: '600',
  },
  input: { 
    flex: 1, 
    paddingHorizontal: 12, 
    fontSize: 14, 
    color: '#0f172a',
    height: 40,
  },
  searchButton: { 
    width: 40, 
    height: 40, 
    backgroundColor: '#4F46E5', 
    borderRadius: 20, 
    alignItems: 'center', 
    justifyContent: 'center',
  },

  // Toast
  toastContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#fff',
    borderRadius: 16,
    paddingHorizontal: 16,
    paddingVertical: 12,
    marginBottom: 24,
    borderWidth: 1,
    borderColor: '#e2e8f0',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.06,
    shadowRadius: 6,
    elevation: 2,
  },
  toastIcon: {
    width: 36,
    height: 36,
    backgroundColor: '#fed7aa',
    borderRadius: 8,
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 12,
  },
  toastContent: { flex: 1 },
  toastLabel: { fontSize: 12, color: '#64748b', fontWeight: '600', marginBottom: 2 },
  toastUrl: { fontSize: 13, color: '#0f172a', fontWeight: '700' },
  toastButton: {
    backgroundColor: '#4F46E5',
    paddingHorizontal: 14,
    paddingVertical: 6,
    borderRadius: 8,
    marginLeft: 12,
  },
  toastButtonText: { fontSize: 12, fontWeight: '700', color: '#fff' },

  // Scenario Section
  scenarioHeader: {
    fontSize: 11,
    fontWeight: '700',
    color: '#94a3b8',
    marginBottom: 12,
    letterSpacing: 0.5,
    textAlign: 'center'
  },
  scenarioCard: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#fff',
    borderRadius: 16,
    paddingHorizontal: 16,
    paddingVertical: 14,
    marginBottom: 12,
    borderWidth: 1.5,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.08,
    shadowRadius: 6,
    elevation: 2,
  },
  redBorder: { borderColor: '#fee2e2' },
  orangeBorder: { borderColor: '#ffedd5' },
  greenBorder: { borderColor: '#dcfce7' },
  
  scenarioIcon: {
    width: 44,
    height: 44,
    borderRadius: 12,
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 12,
  },
  redIcon: { backgroundColor: '#fef2f2' },
  orangeIcon: { backgroundColor: '#fffbf0' },
  greenIcon: { backgroundColor: '#f0fdf4' },
  
  scenarioText: { flex: 1 },
  scenarioTitle: { fontSize: 14, fontWeight: '700', color: '#0f172a', marginBottom: 2 },
  scenarioSubtitle: { fontSize: 12, color: '#64748b' },

  // Scanning Screen
  center: { flex: 1, alignItems: 'center', justifyContent: 'center', padding: 16 },
  scanTitle: { fontSize: 18, fontWeight: '700', marginTop: 12, color: '#0f172a' },
  scanSubtitle: { color: '#64748b', textAlign: 'center', marginTop: 6, fontSize: 13 },
  logBox: { marginTop: 16, width: '100%', maxHeight: 220, backgroundColor: '#fff', borderRadius: 12, padding: 12, borderWidth: 1, borderColor: '#e6e6e6' },
  logItem: { flexDirection: 'row', alignItems: 'center', marginBottom: 10 },
  logDot: { width: 10, height: 10, borderRadius: 5, backgroundColor: '#4F46E5', marginRight: 10 },
  logText: { color: '#374151', fontSize: 12 },

  // Result Screen
  resultContainer: { flex: 1, backgroundColor: '#f1f5f9' },
  resultScroll: { flex: 1 },
  resultContent: { paddingBottom: 120 },
  resultHeader: {
    paddingTop: 48,
    paddingBottom: 32,
    paddingHorizontal: 24,
    alignItems: 'center',
    borderBottomLeftRadius: 24,
    borderBottomRightRadius: 24,
  },
  dangerBg: { backgroundColor: '#ef4444' },
  safeBg: { backgroundColor: '#16a34a' },
  dangerIconContainer: {
    width: 80,
    height: 80,
    borderRadius: 40,
    backgroundColor: 'rgba(255, 255, 255, 0.18)',
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 16,
  },
  resultTitle: {
    color: '#fff',
    fontSize: 22,
    fontWeight: '700',
    marginBottom: 8,
    textAlign: 'center',
  },
  resultVerdict: {
    color: 'rgba(255, 255, 255, 0.95)',
    fontSize: 14,
    textAlign: 'center',
    lineHeight: 20,
    paddingHorizontal: 16,
  },
  riskBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: 'rgba(255, 255, 255, 0.25)',
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 16,
    marginTop: 12,
    gap: 6,
  },
  riskBadgeText: {
    color: '#fff',
    fontSize: 12,
    fontWeight: '700',
  },

  // Summary Card
  summaryCard: {
    backgroundColor: '#fff',
    borderRadius: 16,
    padding: 16,
    marginHorizontal: 16,
    marginTop: -20,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 8,
    elevation: 4,
  },
  sectionLabel: {
    fontSize: 10,
    fontWeight: '700',
    color: '#94a3b8',
    letterSpacing: 0.5,
    marginBottom: 12,
  },
  summaryRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
  },
  summaryIconBox: {
    width: 40,
    height: 40,
    borderRadius: 12,
    backgroundColor: '#fef2f2',
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 12,
  },
  summaryContent: {
    flex: 1,
  },
  summaryCategory: {
    fontSize: 15,
    fontWeight: '700',
    color: '#0f172a',
    marginBottom: 6,
  },
  impersonatingRow: {
    flexDirection: 'row',
    marginBottom: 4,
  },
  impersonatingLabel: {
    fontSize: 12,
    color: '#64748b',
  },
  impersonatingValue: {
    fontSize: 12,
    fontWeight: '700',
    color: '#0f172a',
  },
  locationRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
  },
  locationText: {
    fontSize: 11,
    color: '#94a3b8',
  },

  // Evidence Card
  evidenceCard: {
    backgroundColor: '#fff',
    borderRadius: 16,
    padding: 16,
    marginHorizontal: 16,
    marginTop: 16,
  },
  evidenceHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 16,
  },
  aiDetectedBadge: {
    fontSize: 10,
    fontWeight: '600',
    color: '#3b82f6',
  },
  evidenceItem: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    marginBottom: 16,
  },
  evidenceIconBox: {
    width: 36,
    height: 36,
    borderRadius: 10,
    backgroundColor: '#f8fafc',
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 12,
  },
  evidenceContent: {
    flex: 1,
  },
  evidenceTitle: {
    fontSize: 14,
    fontWeight: '700',
    color: '#0f172a',
    marginBottom: 4,
  },
  evidenceDesc: {
    fontSize: 12,
    color: '#64748b',
    lineHeight: 18,
  },

  // Guide Card
  guideCard: {
    backgroundColor: '#fff',
    borderRadius: 16,
    padding: 16,
    marginHorizontal: 16,
    marginTop: 12,
  },
  guideItem: {
    flexDirection: 'row',
    marginBottom: 16,
  },
  guideNumber: {
    width: 28,
    height: 28,
    borderRadius: 14,
    backgroundColor: '#fef2f2',
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 12,
  },
  guideNumberText: {
    fontSize: 13,
    fontWeight: '700',
    color: '#ef4444',
  },
  guideContent: {
    flex: 1,
  },
  guideTitle: {
    fontSize: 14,
    fontWeight: '700',
    color: '#b91c1c',
    marginBottom: 4,
  },
  guideDesc: {
    fontSize: 12,
    color: '#64748b',
    lineHeight: 18,
  },

  // Bottom Actions
  bottomActions: {
    position: 'absolute',
    bottom: 0,
    left: 0,
    right: 0,
    flexDirection: 'row',
    padding: 16,
    backgroundColor: '#fff',
    borderTopWidth: 1,
    borderTopColor: '#e2e8f0',
    gap: 12,
  },
  btnSecondary: {
    flex: 1,
    backgroundColor: '#fff',
    paddingVertical: 14,
    borderRadius: 12,
    borderWidth: 1.5,
    borderColor: '#e2e8f0',
    alignItems: 'center',
    justifyContent: 'center',
  },
  btnDanger: {
    flex: 1,
    backgroundColor: '#0f172a',
    paddingVertical: 14,
    borderRadius: 12,
    alignItems: 'center',
    justifyContent: 'center',
  },
  btnText: {
    color: '#0f172a',
    fontWeight: '700',
    fontSize: 14,
  },
  btnTextWhite: {
    color: '#fff',
    fontWeight: '700',
    fontSize: 14,
  },
});
